# SVG
if(SIMPL STREQUAL "libcSVG")
	set(SIMPL_TYPE "libc")
	set(SIMPL_FILES "svg.c")
elseif(SIMPL STREQUAL "SDL3SVG")
	set(SIMPL_TYPE "SDL3")
	set(SIMPL_FILES "svg.c")
elseif(SIMPL STREQUAL "FMODSVG")
	set(SIMPL_TYPE "FMOD")
	set(SIMPL_FILES "svg.c")
# PPM
elseif(SIMPL STREQUAL "libcPPM")
	set(SIMPL_TYPE "libc")
	set(SIMPL_FILES "ppm.c")
elseif(SIMPL STREQUAL "SDL3PPM")
	set(SIMPL_TYPE "SDL3")
	set(SIMPL_FILES "ppm.c")
elseif(SIMPL STREQUAL "FMODPPM")
	set(SIMPL_TYPE "FMOD")
	set(SIMPL_FILES "ppm.c")
else()
	message(FATAL_ERROR "Invalid implementation, the possible values are \"libcSVG\", \"SDL3SVG\", \"FMODSVG\", \"libcPPM\", \"SDL3PPM\", \"FMODPPM\" or \"Dummy\"")
endif()

add_library(SImpl ${SIMPL_FILES})

if(SIMPL_TYPE STREQUAL "libc")
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DSIMPL=1")
elseif(SIMPL_TYPE STREQUAL "SDL3")
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DSIMPL=2")
	find_package(SDL3 REQUIRED)
	target_link_libraries(SImpl SDL3::SDL3)
elseif(SIMPL_TYPE STREQUAL "FMOD")
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DSIMPL=3")
	option(USE_LILE "Build using Lile" OFF)
	if(USE_LILE)
		set(LILE_SRC_PATH "${CMAKE_SOURCE_DIR}/Lile")
		include_directories(${LILE_SRC_PATH})
		add_library(fmod "${LILE_SRC_PATH}/lile.c" "${LILE_SRC_PATH}/fmod.c")
		target_link_libraries(SImpl fmod)
	else()
		if(WIN32)
			set(LIB_EXTENSION ".dll")
		elseif(LINUX)
			set(LIB_EXTENSION ".so")
		elseif(APPLE)
			set(LIB_EXTENSION ".dylib")
		else()
			message(FATAL_ERROR "FMOD: Unsupported platform")
		endif()
		include_directories("$ENV{FMOD_STUDIO_SDK_ROOT}/api/core/inc")
		set(FMOD_LIB_PATH "$ENV{FMOD_STUDIO_SDK_ROOT}/api/core/lib/${CMAKE_SYSTEM_PROCESSOR}")
		target_link_libraries(SImpl "${FMOD_LIB_PATH}/libfmod${LIB_EXTENSION}")
	endif()
endif()