# SVG
if(SIMPL STREQUAL "SDL3SVG")
	find_package(SDL3 REQUIRED)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DSIMPL=2")
	set(SIMPL_FILES "svg.c")
elseif(SIMPL STREQUAL "libcSVG")
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DSIMPL=1")
	set(SIMPL_FILES "svg.c")
# PPM
elseif(SIMPL STREQUAL "SDL3PPM")
	find_package(SDL3 REQUIRED)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DSIMPL=2")
	set(SIMPL_FILES "ppm.c")
elseif(SIMPL STREQUAL "libcPPM")
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DSIMPL=1")
	set(SIMPL_FILES "ppm.c")
else()
	message(FATAL_ERROR "Invalid implementation, the possible values are \"SDL3SVG\", \"libcSVG\", \"SDL3PPM\", \"libcPPM\" or \"Dummy\"")
endif()

add_library(SImpl ${SIMPL_FILES})

if(SIMPL STREQUAL "SDL3SVG" OR SIMPL STREQUAL "SDL3PPM")
	target_link_libraries(SImpl SDL3::SDL3)
endif()