#ifndef __PROGINFO__
#define __PROGINFO__

#define PROGRAM_NAME "BlockBreakC"
#define PROGRAM_VERSION "1.2pre"

#ifndef RENDER_WIDTH
	#define RENDER_WIDTH 640
#endif
#ifndef RENDER_HEIGHT
	#define RENDER_HEIGHT 472
#endif

#ifndef PLAYER_SPEED
	#define PLAYER_SPEED RENDER_HEIGHT / 59
#endif
#ifndef PLAYER_WIDTH
	#define PLAYER_WIDTH RENDER_WIDTH / 40
#endif
#ifndef PLAYER_HEIGHT
	#define PLAYER_HEIGHT RENDER_WIDTH / 40
#endif
#define PLAYER_START_X (RENDER_WIDTH / 2) - (PLAYER_WIDTH / 2)
#define PLAYER_START_Y RENDER_HEIGHT - (PLAYER_HEIGHT * 3)
#if PLAYER_SPEED < 1
	#undef PLAYER_SPEED
	#define PLAYER_SPEED 1
#endif
#if PLAYER_WIDTH < 1
	#undef PLAYER_WIDTH
	#define PLAYER_WIDTH 1
#endif
#if PLAYER_HEIGHT < 1
	#undef PLAYER_HEIGHT
	#define PLAYER_HEIGHT 1
#endif

#define SCREEN_EDGE_UP 0
#define SCREEN_EDGE_DOWN RENDER_HEIGHT - PLAYER_HEIGHT
#define SCREEN_EDGE_LEFT 0
#define SCREEN_EDGE_RIGHT RENDER_WIDTH - PLAYER_WIDTH

#ifndef MAX_BLOCKS
	#define MAX_BLOCKS 255
#endif
#define MAX_FPS 30

#endif