name: C - Build
on: [push, pull_request]
jobs:
  build:
    name: Build ${{matrix.build-targets.name}}
    runs-on: ${{matrix.build-targets.os}}
    strategy:
      matrix:
        build-targets:
          - {
            name: "SDL3 - Linux (x64)",
            os: "ubuntu-latest",
            impl: "SDL3",
            output: "BlockBreakC-SDL3-Linux-x64",
            upload: "BlockBreakC"
          }
          - {
            name: "FreeGLUT (GLUT) - Linux (x64)",
            os: "ubuntu-latest",
            impl: "GLUT",
            output: "BlockBreakC-FreeGLUT-Linux-x64",
            upload: "BlockBreakC"
          }
          - {
            name: "SDL3 + GL - Linux (x64)",
            os: "ubuntu-latest",
            impl: "SDL3GL",
            output: "BlockBreakC-SDL3GL-Linux-x64",
            upload: "BlockBreakC"
          }
    steps:
      - uses: actions/checkout@v4
      
      - name: Update Package Lists
        run: sudo apt-get update
      
      # SDL3 (+ GL)
      - uses: libsdl-org/setup-sdl@main
        if: ${{matrix.build-targets.impl == 'SDL3' || matrix.build-targets.impl == 'SDL3GL'}}
        id: sdl
        with:
          install-linux-dependencies: true
          version: 3-latest
      
      # FreeGLUT
      - name: FreeGLUT - Install
        if: matrix.build-targets.impl == 'GLUT'
        run: sudo apt-get install freeglut3-dev
      
      - name: Configure CMake
        run: >
          cmake -S .
          -DCMAKE_C_COMPILER=gcc
          -DCMAKE_BUILD_TYPE=Release
          -DIMPL=${{matrix.build-targets.impl}}
          -G "Unix Makefiles"
      
      - name: Build
        run: cmake --build .
      
      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.build-targets.output}}
          path: |
            ${{matrix.build-targets.upload}}
            LICENSE